# Generated by Django 4.2.5 on 2026-03-28 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelemetryIdentity',
            fields=[
                ('record_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('race_id', models.TextField()),
                ('frame_id', models.TextField()),
                ('ts_ns', models.BigIntegerField()),
                ('topic_name', models.TextField()),
                ('source_seq', models.BigIntegerField(default=-1)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'telemetry_identity',
            },
        ),
        migrations.CreateModel(
            name='TopicBadenia560TpmsFront',
            fields=[
                ('record', models.OneToOneField(db_column='record_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='topic_badenia_560_tpms_front', serialize=False, to='telemetry.telemetryidentity')),
                ('tpr4_temp_fl', models.FloatField(null=True)),
                ('tpr4_temp_fr', models.FloatField(null=True)),
                ('tpr4_abs_press_fr', models.FloatField(null=True)),
                ('tpr4_abs_press_fl', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'topic_badenia_560_tpms_front',
            },
        ),
        migrations.CreateModel(
            name='TopicBadenia560TpmsRear',
            fields=[
                ('record', models.OneToOneField(db_column='record_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='topic_badenia_560_tpms_rear', serialize=False, to='telemetry.telemetryidentity')),
                ('tpr4_temp_rl', models.FloatField(null=True)),
                ('tpr4_temp_rr', models.FloatField(null=True)),
                ('tpr4_abs_press_rl', models.FloatField(null=True)),
                ('tpr4_abs_press_rr', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'topic_badenia_560_tpms_rear',
            },
        ),
        migrations.CreateModel(
            name='TopicBadenia560TyreSurfaceTempFront',
            fields=[
                ('record', models.OneToOneField(db_column='record_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='topic_badenia_560_tyre_surface_temp_front', serialize=False, to='telemetry.telemetryidentity')),
                ('outer_fl', models.FloatField(null=True)),
                ('center_fl', models.FloatField(null=True)),
                ('inner_fl', models.FloatField(null=True)),
                ('outer_fr', models.FloatField(null=True)),
                ('center_fr', models.FloatField(null=True)),
                ('inner_fr', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'topic_badenia_560_tyre_surface_temp_front',
            },
        ),
        migrations.CreateModel(
            name='TopicBadenia560TyreSurfaceTempRear',
            fields=[
                ('record', models.OneToOneField(db_column='record_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='topic_badenia_560_tyre_surface_temp_rear', serialize=False, to='telemetry.telemetryidentity')),
                ('outer_rl', models.FloatField(null=True)),
                ('center_rl', models.FloatField(null=True)),
                ('inner_rl', models.FloatField(null=True)),
                ('outer_rr', models.FloatField(null=True)),
                ('center_rr', models.FloatField(null=True)),
                ('inner_rr', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'topic_badenia_560_tyre_surface_temp_rear',
            },
        ),
        migrations.CreateModel(
            name='TopicCbaStatusFl',
            fields=[
                ('record', models.OneToOneField(db_column='record_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='topic_cba_status_fl', serialize=False, to='telemetry.telemetryidentity')),
                ('cba_actual_pressure_fl_pa', models.FloatField(null=True)),
                ('cba_actual_pressure_fl', models.FloatField(null=True)),
                ('cba_target_pressure_fl_ack', models.FloatField(null=True)),
                ('cba_actual_current_fl_a', models.FloatField(null=True)),
                ('cba_voltage_fl_v', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'topic_cba_status_fl',
            },
        ),
        migrations.CreateModel(
            name='TopicCbaStatusFr',
            fields=[
                ('record', models.OneToOneField(db_column='record_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='topic_cba_status_fr', serialize=False, to='telemetry.telemetryidentity')),
                ('cba_actual_pressure_fr_pa', models.FloatField(null=True)),
                ('cba_actual_pressure_fr', models.FloatField(null=True)),
                ('cba_target_pressure_fr_ack', models.FloatField(null=True)),
                ('cba_actual_current_fr_a', models.FloatField(null=True)),
                ('cba_voltage_fr_v', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'topic_cba_status_fr',
            },
        ),
        migrations.CreateModel(
            name='TopicCbaStatusRl',
            fields=[
                ('record', models.OneToOneField(db_column='record_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='topic_cba_status_rl', serialize=False, to='telemetry.telemetryidentity')),
                ('cba_actual_pressure_rl_pa', models.FloatField(null=True)),
                ('cba_actual_pressure_rl', models.FloatField(null=True)),
                ('cba_target_pressure_rl_ack', models.FloatField(null=True)),
                ('cba_actual_current_rl_a', models.FloatField(null=True)),
                ('cba_voltage_rl_v', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'topic_cba_status_rl',
            },
        ),
        migrations.CreateModel(
            name='TopicCbaStatusRr',
            fields=[
                ('record', models.OneToOneField(db_column='record_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='topic_cba_status_rr', serialize=False, to='telemetry.telemetryidentity')),
                ('cba_actual_pressure_rr_pa', models.FloatField(null=True)),
                ('cba_actual_pressure_rr', models.FloatField(null=True)),
                ('cba_target_pressure_rr_ack', models.FloatField(null=True)),
                ('cba_actual_current_rr_a', models.FloatField(null=True)),
                ('cba_voltage_rr_v', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'topic_cba_status_rr',
            },
        ),
        migrations.CreateModel(
            name='TopicHlMsg01',
            fields=[
                ('record', models.OneToOneField(db_column='record_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='topic_hl_msg_01', serialize=False, to='telemetry.telemetryidentity')),
                ('hl_alive_01', models.SmallIntegerField(null=True)),
                ('hl_target_pressure_rr', models.FloatField(null=True)),
                ('hl_target_pressure_rl', models.FloatField(null=True)),
                ('hl_target_pressure_fr', models.FloatField(null=True)),
                ('hl_target_pressure_fl', models.FloatField(null=True)),
                ('hl_target_gear', models.SmallIntegerField(null=True)),
                ('hl_target_throttle', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'topic_hl_msg_01',
            },
        ),
        migrations.CreateModel(
            name='TopicHlMsg02',
            fields=[
                ('record', models.OneToOneField(db_column='record_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='topic_hl_msg_02', serialize=False, to='telemetry.telemetryidentity')),
                ('hl_alive_02', models.SmallIntegerField(null=True)),
                ('hl_psa_mode_of_operation', models.SmallIntegerField(null=True)),
                ('hl_target_psa_control', models.FloatField(null=True)),
                ('hl_psa_profile_acc_rad_s2', models.IntegerField(null=True)),
                ('hl_psa_profile_dec_rad_s2', models.IntegerField(null=True)),
                ('hl_psa_profile_vel_rad_s', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'topic_hl_msg_02',
            },
        ),
        migrations.CreateModel(
            name='TopicIceStatus01',
            fields=[
                ('record', models.OneToOneField(db_column='record_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='topic_ice_status_01', serialize=False, to='telemetry.telemetryidentity')),
                ('ice_actual_gear', models.FloatField(null=True)),
                ('ice_target_gear_ack', models.FloatField(null=True)),
                ('ice_actual_throttle', models.FloatField(null=True)),
                ('ice_target_throttle_ack', models.FloatField(null=True)),
                ('ice_push_to_pass_req', models.FloatField(null=True)),
                ('ice_push_to_pass_ack', models.FloatField(null=True)),
                ('ice_water_press_k_pa', models.FloatField(null=True)),
                ('ice_available_fuel_l', models.FloatField(null=True)),
                ('ice_downshift_available', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'topic_ice_status_01',
            },
        ),
        migrations.CreateModel(
            name='TopicIceStatus02',
            fields=[
                ('record', models.OneToOneField(db_column='record_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='topic_ice_status_02', serialize=False, to='telemetry.telemetryidentity')),
                ('ice_oil_temp_deg_c', models.FloatField(null=True)),
                ('ice_engine_speed_rpm', models.FloatField(null=True)),
                ('ice_fuel_press_k_pa', models.FloatField(null=True)),
                ('ice_water_temp_deg_c', models.FloatField(null=True)),
                ('ice_oil_press_k_pa', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'topic_ice_status_02',
            },
        ),
        migrations.CreateModel(
            name='TopicKistlerAccBody',
            fields=[
                ('record', models.OneToOneField(db_column='record_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='topic_kistler_acc_body', serialize=False, to='telemetry.telemetryidentity')),
                ('acc_x_body', models.FloatField(null=True)),
                ('acc_y_body', models.FloatField(null=True)),
                ('acc_z_body', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'topic_kistler_acc_body',
            },
        ),
        migrations.CreateModel(
            name='TopicKistlerAngVelBody',
            fields=[
                ('record', models.OneToOneField(db_column='record_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='topic_kistler_ang_vel_body', serialize=False, to='telemetry.telemetryidentity')),
                ('ang_vel_x_body', models.FloatField(null=True)),
                ('ang_vel_y_body', models.FloatField(null=True)),
                ('ang_vel_z_body', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'topic_kistler_ang_vel_body',
            },
        ),
        migrations.CreateModel(
            name='TopicKistlerCorrevit',
            fields=[
                ('record', models.OneToOneField(db_column='record_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='topic_kistler_correvit', serialize=False, to='telemetry.telemetryidentity')),
                ('vel_x_cor', models.FloatField(null=True)),
                ('vel_y_cor', models.FloatField(null=True)),
                ('vel_cor', models.FloatField(null=True)),
                ('angle_cor', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'topic_kistler_correvit',
            },
        ),
        migrations.CreateModel(
            name='TopicPsaStatus01',
            fields=[
                ('record', models.OneToOneField(db_column='record_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='topic_psa_status_01', serialize=False, to='telemetry.telemetryidentity')),
                ('psa_actual_pos_rad', models.FloatField(null=True)),
                ('psa_actual_speed_rad_s', models.FloatField(null=True)),
                ('psa_actual_torque_m_nm', models.FloatField(null=True)),
                ('psa_actual_mode_of_operation', models.SmallIntegerField(null=True)),
                ('psa_actual_current_a', models.FloatField(null=True)),
                ('psa_actual_voltage_v', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'topic_psa_status_01',
            },
        ),
        migrations.CreateModel(
            name='TopicPsaStatus02',
            fields=[
                ('record', models.OneToOneField(db_column='record_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='topic_psa_status_02', serialize=False, to='telemetry.telemetryidentity')),
                ('psa_target_psa_control_ack', models.FloatField(null=True)),
                ('psa_actual_pos', models.FloatField(null=True)),
                ('psa_actual_speed', models.FloatField(null=True)),
                ('psa_actual_torque', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'topic_psa_status_02',
            },
        ),
        migrations.CreateModel(
            name='TopicStateEstimation',
            fields=[
                ('record', models.OneToOneField(db_column='record_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='topic_state_estimation', serialize=False, to='telemetry.telemetryidentity')),
                ('x_m', models.FloatField(null=True)),
                ('y_m', models.FloatField(null=True)),
                ('z_m', models.FloatField(null=True)),
                ('roll_rad', models.FloatField(null=True)),
                ('pitch_rad', models.FloatField(null=True)),
                ('yaw_rad', models.FloatField(null=True)),
                ('wx_radps', models.FloatField(null=True)),
                ('wy_radps', models.FloatField(null=True)),
                ('wz_radps', models.FloatField(null=True)),
                ('vx_mps', models.FloatField(null=True)),
                ('vy_mps', models.FloatField(null=True)),
                ('vz_mps', models.FloatField(null=True)),
                ('omega_w_fl', models.FloatField(null=True)),
                ('omega_w_fr', models.FloatField(null=True)),
                ('omega_w_rl', models.FloatField(null=True)),
                ('omega_w_rr', models.FloatField(null=True)),
                ('v_mps', models.FloatField(null=True)),
                ('v_raw_mps', models.FloatField(null=True)),
                ('ax_mps2', models.FloatField(null=True)),
                ('ay_mps2', models.FloatField(null=True)),
                ('az_mps2', models.FloatField(null=True)),
                ('yaw_vel_rad', models.FloatField(null=True)),
                ('kappa_radpm', models.FloatField(null=True)),
                ('dbeta_radps', models.FloatField(null=True)),
                ('ddyaw_radps2', models.FloatField(null=True)),
                ('ax_vel_mps2', models.FloatField(null=True)),
                ('ay_vel_mps2', models.FloatField(null=True)),
                ('lambda_fl_perc', models.FloatField(null=True)),
                ('lambda_fr_perc', models.FloatField(null=True)),
                ('lambda_rl_perc', models.FloatField(null=True)),
                ('lambda_rr_perc', models.FloatField(null=True)),
                ('valid_wheelsspeeds_b', models.BooleanField(null=True)),
                ('alpha_fl_rad', models.FloatField(null=True)),
                ('alpha_fr_rad', models.FloatField(null=True)),
                ('alpha_rl_rad', models.FloatField(null=True)),
                ('alpha_rr_rad', models.FloatField(null=True)),
                ('diff_fr_alpha_rad', models.FloatField(null=True)),
                ('delta_wheel_rad', models.FloatField(null=True)),
                ('timestamp', models.FloatField(null=True)),
                ('gas', models.FloatField(null=True)),
                ('brake', models.FloatField(null=True)),
                ('clutch', models.FloatField(null=True)),
                ('gear', models.FloatField(null=True)),
                ('rpm', models.FloatField(null=True)),
                ('front_brake_pressure', models.FloatField(null=True)),
                ('rear_brake_pressure', models.FloatField(null=True)),
                ('vehicle_timestamp', models.FloatField(null=True)),
                ('cba_actual_pressure_fl_pa', models.FloatField(null=True)),
                ('cba_actual_pressure_fr_pa', models.FloatField(null=True)),
                ('cba_actual_pressure_rl_pa', models.FloatField(null=True)),
                ('cba_actual_pressure_rr_pa', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'topic_state_estimation',
            },
        ),
        migrations.CreateModel(
            name='TopicWheelsSpeed01',
            fields=[
                ('record', models.OneToOneField(db_column='record_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='topic_wheels_speed_01', serialize=False, to='telemetry.telemetryidentity')),
                ('wss_speed_fl_rad_s', models.FloatField(null=True)),
                ('wss_speed_fr_rad_s', models.FloatField(null=True)),
                ('wss_speed_rl_rad_s', models.FloatField(null=True)),
                ('wss_speed_rr_rad_s', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'topic_wheels_speed_01',
            },
        ),
        migrations.AddIndex(
            model_name='telemetryidentity',
            index=models.Index(fields=['race_id', 'ts_ns'], name='ix_identity_race_ts'),
        ),
        migrations.AddIndex(
            model_name='telemetryidentity',
            index=models.Index(fields=['topic_name', 'ts_ns'], name='ix_identity_topic_ts'),
        ),
        migrations.AddConstraint(
            model_name='telemetryidentity',
            constraint=models.UniqueConstraint(fields=('race_id', 'topic_name', 'ts_ns', 'frame_id', 'source_seq'), name='uq_identity_race_topic_ts_frame_seq'),
        ),
    ]
