# Generated by Django 4.2.5 on 2026-03-28 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicTfTransform',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('transform_index', models.IntegerField()),
                ('parent_frame_id', models.TextField()),
                ('child_frame_id', models.TextField()),
                ('stamp_ns', models.BigIntegerField()),
                ('translation_x', models.FloatField(null=True)),
                ('translation_y', models.FloatField(null=True)),
                ('translation_z', models.FloatField(null=True)),
                ('rotation_x', models.FloatField(null=True)),
                ('rotation_y', models.FloatField(null=True)),
                ('rotation_z', models.FloatField(null=True)),
                ('rotation_w', models.FloatField(null=True)),
                ('record', models.ForeignKey(db_column='record_id', on_delete=django.db.models.deletion.CASCADE, related_name='topic_tf_transforms', to='telemetry.telemetryidentity')),
            ],
            options={
                'db_table': 'topic_tf_transform',
                'indexes': [models.Index(fields=['parent_frame_id', 'child_frame_id'], name='ix_tf_parent_child'), models.Index(fields=['stamp_ns'], name='ix_tf_stamp_ns')],
            },
        ),
        migrations.AddConstraint(
            model_name='topictftransform',
            constraint=models.UniqueConstraint(fields=('record', 'transform_index'), name='uq_tf_record_transform_index'),
        ),
    ]
