# Generated by Django 4.2.5 on 2026-03-28 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0002_topictftransform_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='telemetryidentity',
            index=models.Index(fields=['race_id', 'topic_name', 'ts_ns'], name='ix_identity_race_topic_ts'),
        ),
    ]
