# Generated by Django 4.2.5 on 2026-03-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0003_telemetryidentity_ix_identity_race_topic_ts'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_id', models.TextField()),
                ('camera', models.IntegerField()),
                ('frame_number', models.IntegerField()),
                ('timestamp_seconds', models.FloatField()),
                ('fps', models.IntegerField()),
                ('file_path', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'camera_frame',
                'indexes': [models.Index(fields=['race_id', 'camera'], name='ix_camera_frame_race_camera'), models.Index(fields=['race_id', 'camera', 'timestamp_seconds'], name='ix_camera_frame_race_camera_ts')],
            },
        ),
        migrations.AddConstraint(
            model_name='cameraframe',
            constraint=models.UniqueConstraint(fields=('race_id', 'camera', 'frame_number'), name='uq_camera_frame_race_camera_frame_number'),
        ),
    ]
