# Generated by Django 4.2.5 on 2026-03-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0004_cameraframe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraFrameSQLiteBlob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_id', models.TextField()),
                ('camera', models.IntegerField()),
                ('frame_number', models.IntegerField()),
                ('timestamp_seconds', models.FloatField()),
                ('timestamp_ns', models.BigIntegerField()),
                ('x_m', models.FloatField(null=True)),
                ('y_m', models.FloatField(null=True)),
                ('z_m', models.FloatField(null=True)),
                ('telemetry_race_id', models.TextField(null=True)),
                ('telemetry_ts_ns', models.BigIntegerField(null=True)),
                ('file_path', models.TextField()),
                ('image_format', models.CharField(default='jpg', max_length=16)),
                ('image_size_bytes', models.IntegerField()),
                ('image_blob', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'camera_frame_sqlite_blob',
                'indexes': [models.Index(fields=['race_id', 'camera'], name='ix_cam_blob_race_cam'), models.Index(fields=['race_id', 'camera', 'timestamp_ns'], name='ix_cam_blob_race_cam_tsns')],
            },
        ),
        migrations.AddConstraint(
            model_name='cameraframesqliteblob',
            constraint=models.UniqueConstraint(fields=('race_id', 'camera', 'frame_number'), name='uq_cam_blob_race_cam_frame'),
        ),
    ]
